### ISSUE TITLE
Big Bass Bonanza

### ISSUE THREAD

**Issue by UbuntuEvangelist** [gamingdotme/opensource-casino-v10#2]
how to add Big Bass Bonanza into this game? we have setup this script using this service ---redacted Youtube Telegram promotional link---  but not able to add game.

![Screenshot from 2023-10-14 17-48-48](https://github.com/gamingdotme/opensource-casino-v9/assets/1058663/5133bf79-fa40-4f98-8eb8-5f6e4b085a81)

**Comment by gamingdotme** [comment]
so that services takes a free game script and sell it for hundreds, and you ask us for free support 
A bit ironic no ? 
I mean if you paid them, for a free script, why arent they offering support ?

However, we dont ask who are you, still anybody welcome to discord to discuss or update or ask for free.
